# -*- coding: utf-8 -*-
"""Untitled38.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-4le0UldM-FCIwftUMpPC7YKRrDE9nPj
"""

x = input()



end_words = ['esc', 'stop', 'exit', 'quit']

def lowercase(sentence):
  return sentence.loweer()

def uppercase(sentence):
  return sentence.upper()

x = input()
while x not in end_words:
  choice = input()
  if choice == '1':
    print(lowercase(x))
  elif choice == '2':
    print(uppercase(x))
  else:
    print('invalid choice')
  x = input()

x = input()
while x not in end_words:
  choice = input()
  if choice == '1':
    print(lowercase(x))
  elif choice == '2':
    print(uppercase(x))
  else:
    print('invalid choice')
  x = input()

x = input('Enter text')
while x not in end_words:
  choice = input()
  if choice == '1':
    print(lowercase(x))
  elif choice == '2':
    print(uppercase(x))
  elif choice == '3':
    print(swapcase(x))
  else:
    print('invalid choice')
  x = input

